# Generated by Django 5.1.3 on 2024-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='text',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='update_date',
        ),
        migrations.AddField(
            model_name='sms',
            name='characteristic',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sms',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sms',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sms',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='product',
            field=models.CharField(default='', max_length=200),
        ),
    ]
