# Generated by Django 5.1.3 on 2024-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sms_publish_date_remove_sms_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
