# Generated by Django 5.1.3 on 2024-11-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sms_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=200, verbose_name='متن لوگو ها')),
                ('header_p', models.CharField(max_length=800, verbose_name='متن بالای صفحه')),
                ('search_u_p', models.CharField(max_length=800, verbose_name='متن بالای باکس سرچ')),
                ('search_d_p', models.CharField(max_length=800, verbose_name='متن پایین باکس سرچ')),
                ('add_u_p', models.CharField(max_length=800, verbose_name='متن بالای باکس ادد')),
                ('add_d_p', models.CharField(max_length=800, verbose_name='متن پایین باکس ادد')),
                ('field_1', models.CharField(max_length=100, verbose_name='متن جای خالی اول')),
                ('field_2', models.CharField(max_length=100, verbose_name='متن جای خالی دوم')),
                ('field_3', models.CharField(max_length=100, verbose_name='متن جای خالی سوم')),
            ],
        ),
    ]
