# Generated by Django 5.1.3 on 2024-11-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_content_add_d_p_alter_content_add_u_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='date',
        ),
        migrations.AddField(
            model_name='sms',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sms',
            name='month',
            field=models.CharField(choices=[('1', 'فروردین'), ('2', 'اردیبهشت'), ('3', 'خرداد'), ('4', 'تیر'), ('5', 'مرداد'), ('6', 'شهریور'), ('7', 'مهر'), ('8', 'آبان'), ('9', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='sms',
            name='year',
            field=models.IntegerField(default=1403),
        ),
    ]
