# Generated by Django 5.1.3 on 2024-11-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_sms_date_sms_day_sms_month_sms_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='field_4',
            field=models.TextField(default='', max_length=100, verbose_name='متن جای خالی چهارم'),
        ),
    ]
