# Generated by Django 5.1.3 on 2024-11-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_full_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
